#application.yml
server:
    port: 28080
logging:
    config: classpath:log4j2-test.xml
spring:
    profiles:
        active: test
webmagic:
    download:
        path: /home/demo-webmagic-web/download