#application.yml
 
server:
    port: 80
    tomcat:
        uri-encoding: UTF-8

spring:
    profiles:
        active: #spring.profiles.active#
    main:
        allow-bean-definition-overriding: true
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    datasource:
        url: jdbc:mysql://192.168.7.124:3306/demo?serverTimezone=UTC&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
        username: root
        password: root

mybatis:
    mapper-locations:
        classpath: com/linw/demo/mapper/*.xml
    type-aliases-package: com.linw.demo.entity